### ISSUE TITLE
Error in Calculating Blinking Period

### ISSUE THREAD

**Issue by spusuluri** [spusuluri/bme590_lab8_code#3]
https://github.com/spusuluri/bme590_lab8_code/blob/4c91db0dbfe41a3529719258bc3ca700522d1401/src/main.c#L416

In the function above, I'm trying to calculate the blink period to feed into the k_timer_start for that led. The code is currently trying to calculate the blinking frequency of the 1st ADC Channel. I'm trying to log the slope of the line but doesn't seem to work. It outputs %f instead of the value. I'm trying to use typecasting to output an integer of the blinking period in milliseconds. I'm not sure how to properly calculate the value and why the slope is being outputted.

**Comment by mlp6** [comment]
By default, the logging output does not support floating point values.  I think you need to load in the configuration that supports that in `prj.conf` with `CONFIG_CBPRINTF_FP_SUPPORT=y`

**Comment by mlp6** [comment]
Also make sure that all of the variables in your float math are floats and not a mix of ints and floats (i.e., typecast all variables).  Helps avoid some "gotchas".

**Comment by spusuluri** [comment]
That did the trick. Calculations are correct.
